name = "Ginger-and-Sugar"
author = "R&J"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0fbf79de1c2940c013a4b251d2032c8f0a43f251ba7469064a220a542c30b75"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
