name = "Ginger-and-Sugar"
author = "R&J"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7837910ed5126541b35c671cd497d715796ae9b17f96e2c91c0fd230b3e4309"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
